import { Sparkles, TrendingUp, MapPin, ShieldCheck, Users } from "lucide-react";

export default function AIInsights({ brief }) {
  const insights = [
    {
      icon: <TrendingUp size={18} />,
      title: `${brief.top_product} demand is highest today`,
      color: "text-blue-600",
    },
    {
      icon: <MapPin size={18} />,
      title: `${brief.top_city} has the strongest opportunity`,
      color: "text-green-600",
    },
    {
      icon: <Users size={18} />,
      title: `${brief.immediate_followups} customers need immediate follow-up`,
      color: "text-orange-600",
    },
    {
      icon: <ShieldCheck size={18} />,
      title: `${brief.conversion_potential_percent}% estimated conversion potential`,
      color: "text-purple-600",
    },
  ];

  return (
    <div className="bg-white rounded-3xl shadow-sm border border-slate-100 p-6">
      <div className="flex items-center gap-3 mb-5">
        <div className="bg-blue-100 p-3 rounded-2xl">
          <Sparkles className="text-blue-700" />
        </div>

        <div>
          <h2 className="text-xl font-bold">AI Insights</h2>
          <p className="text-slate-500 text-sm">
            Generated by Prospect Assist AI
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {insights.map((item, index) => (
          <div
            key={index}
            className="flex items-start gap-3 border-b border-slate-100 pb-4 last:border-0"
          >
            <div className={item.color}>{item.icon}</div>

            <p className="text-slate-700">{item.title}</p>
          </div>
        ))}
      </div>

      <div className="mt-6 bg-blue-50 rounded-2xl p-4">
        <p className="text-sm text-blue-700 font-semibold">
          AI Confidence Score
        </p>

        <div className="mt-3 bg-white rounded-full h-3 overflow-hidden">
          <div
            className="bg-blue-600 h-full rounded-full"
            style={{ width: "96%" }}
          />
        </div>

        <p className="text-blue-700 font-bold mt-2">96%</p>
      </div>
    </div>
  );
}
