from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from .customer_data import get_customer_by_id
from .intelligence import calculate_prospect_intelligence
from .recommendation import recommend_loan_product
from .explanation import generate_customer_explanation


REPORT_DIR = Path(__file__).resolve().parents[3] / "reports"
REPORT_DIR.mkdir(exist_ok=True)


def generate_customer_pdf(customer_id: str):
    customer = get_customer_by_id(customer_id)

    if customer is None:
        return None

    intelligence = calculate_prospect_intelligence(customer)
    recommendation = recommend_loan_product(customer, intelligence)
    explanation = generate_customer_explanation(
        customer,
        intelligence,
        recommendation
    )

    file_path = REPORT_DIR / f"{customer_id}_report.pdf"

    c = canvas.Canvas(str(file_path), pagesize=A4)
    width, height = A4
    y = height - 50

    def line(text, size=11, gap=18):
        nonlocal y
        c.setFont("Helvetica", size)
        safe_text = str(text).replace("₹", "Rs. ")
        c.drawString(50, y, safe_text)
        y -= gap

    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, y, "Prospect Assist AI - Customer Report")
    y -= 40

    line(f"Customer ID: {customer['customer_id']}", 12)
    line(f"City: {customer['city']}", 12)
    line(f"Employment Type: {customer['employment_type']}", 12)
    line(f"Monthly Income: Rs. {customer['monthly_income']}", 12)
    line(f"CIBIL Score: {customer['cibil_score']}", 12)
    line(f"FOIR: {customer['foir']}", 12)

    y -= 10
    c.setFont("Helvetica-Bold", 15)
    c.drawString(50, y, "AI Prospect Intelligence")
    y -= 25

    line(f"Prospect Score: {intelligence['overall_prospect_score']}/100")
    line(f"Category: {intelligence['prospect_category']}")
    line(f"Risk Level: {intelligence['risk_level']}")
    line(f"Recommended Product: {recommendation['recommended_product']}")
    line(f"Priority: {recommendation['priority']}")

    y -= 10
    c.setFont("Helvetica-Bold", 15)
    c.drawString(50, y, "Key Reasons")
    y -= 25

    for reason in explanation["key_reasons"][:8]:
        line(f"- {reason}", 10)

    y -= 10
    c.setFont("Helvetica-Bold", 15)
    c.drawString(50, y, "Relationship Manager Note")
    y -= 25

    note = explanation["relationship_manager_note"]
    words = note.split()
    current = ""

    for word in words:
        if len(current + " " + word) < 90:
            current += " " + word
        else:
            line(current.strip(), 10)
            current = word

    if current:
        line(current.strip(), 10)

    y -= 20
    line("Generated by Prospect Assist AI", 9)

    c.save()

    return file_path
